In [1]:
import numpy  as np
import pandas as pd

In [2]:
df = pd.read_csv("./dataset.csv/anime.csv")
synopsis = pd.read_csv("./dataset.csv/anime_with_synopsis.csv")

In [3]:
#cleaning the data
df.dropna(inplace=True) 
synopsis.dropna(inplace=True)
synopsis =synopsis[['Name','sypnopsis']]

In [4]:
df = df.merge(synopsis, on='Name')

In [5]:
df = df[['MAL_ID','Name','Genres','sypnopsis','Type','Studios','Rating']]

In [6]:
df

,MAL_ID,Name,Genres,sypnopsis,Type,Studios,Rating
0,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever...",TV,Sunrise,R - 17+ (violence & profanity)
1,5,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ...",Movie,Bones,R - 17+ (violence & profanity)
2,6,Trigun,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0...",TV,Madhouse,PG-13 - Teens 13 or older
3,7,Witch Hunter Robin,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...,TV,Sunrise,PG-13 - Teens 13 or older
4,8,Bouken Ou Beet,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...,TV,Toei Animation,PG - Children
...,...,...,...,...,...,...,...
16211,48481,Daomu Biji Zhi Qinling Shen Shu,"Adventure, Mystery, Supernatural",No synopsis information has been added to this...,ONA,Unknown,Unknown
16212,48483,Mieruko-chan,"Comedy, Horror, Supernatural",ko is a typical high school student whose life...,TV,Passione,Unknown
16213,48488,Higurashi no Naku Koro ni Sotsu,"Mystery, Dementia, Horror, Psychological, Supe...",Sequel to Higurashi no Naku Koro ni Gou .,TV,Unknown,R - 17+ (violence & profanity)
16214,48491,Yama no Susume: Next Summit,"Adventure, Slice of Life, Comedy",New Yama no Susume anime.,TV,8bit,PG-13 - Teens 13 or older
16215,48492,Scarlet Nexus,"Action, Fantasy",Solar calendar year 2020: grotesque organisms ...,TV,Sunrise,Unknown

In [8]:
# Ik animes without synopsis and genre data are small therefore drop 'em
df = df[~((df['sypnopsis'].str.contains("No synopsis information has been added to this")) & (df['Genres'] == 'Unknown'))]

In [14]:
no_sypn = df[df['sypnopsis'].str.contains("No synopsis information has been added to this")]
no_sypn['sypnopsis'][2225]

'No synopsis information has been added to this title. Help improve our database by adding a synopsis here .'

In [15]:
df_clean = df.replace('Unknown', np.nan)
df_clean = df_clean.replace('No synopsis information has been added to this title. Help improve our database by adding a synopsis here .',np.nan)

In [29]:
no_sypn = df_clean[df_clean['sypnopsis'].isna()]
no_sypn

,MAL_ID,Name,Genres,sypnopsis,Type,Studios,Rating
2225,2626,The☆Doraemons: Mushimushi Pyonpyon Daisakusen!,Fantasy,NaN,Movie,Shin-Ei Animation,PG - Children
2226,2627,Doraemon: It's New Year!,"Kids, Comedy, Sci-Fi, Shounen",NaN,Special,NaN,PG - Children
2227,2628,"The☆Doraemons: Strange, Sweets, Strange?",Fantasy,NaN,Movie,Shin-Ei Animation,PG - Children
2228,2629,Doraemon and Itchy the Stray,"Comedy, Kids, Sci-Fi, Shounen",NaN,Special,NaN,PG - Children
2231,2632,Doraemon: Time Machine de Oshougatsu,"Sci-Fi, Adventure, Comedy, Kids, Shounen",NaN,Special,NaN,PG - Children
...,...,...,...,...,...,...,...
16175,48097,Wan Jie Qi Yuan,"Martial Arts, Fantasy",NaN,ONA,Ruo Hong Culture,PG-13 - Teens 13 or older
16201,48426,Kitarou Tanjou: Gegege no Nazo,"Comedy, Demons, Supernatural, Shounen",NaN,Movie,NaN,NaN
16205,48442,Shikaru Neko,Slice of Life,NaN,TV,NaN,NaN
16210,48480,Wan Jie Shen Zhu 3rd Season,"Adventure, Fantasy",NaN,ONA,NaN,NaN
16211,48481,Daomu Biji Zhi Qinling Shen Shu,"Adventure, Mystery, Supernatural",NaN,ONA,NaN,NaN

In [30]:
df_clean['Genres'] = df_clean['Genres'].fillna('')
df_clean['sypnopsis'] = df_clean['sypnopsis'].fillna('')
df_clean['Rating'] = df_clean['Rating'].fillna('')
df_clean['Type'] = df_clean['Type'].fillna('')
df_clean['Studios'] = df_clean['Studios'].fillna('')

In [31]:
df_clean['Rating'] = df_clean['Rating'].replace('R - 17+ (violence & profanity)', '17+')
df_clean['Rating'] = df_clean['Rating'].replace('PG-13 - Teens 13 or older', 'PG-13')
df_clean['Rating'] = df_clean['Rating'].replace('PG - Children', 'PG')
df_clean['Rating'] = df_clean['Rating'].replace('G - All Ages', 'G')
df_clean['Rating'] = df_clean['Rating'].replace('R+ - Mild Nudity', 'R+')

In [32]:
df_clean['Genres'] = df_clean['Genres'].apply(lambda x:x.split(','))
df_clean['sypnopsis'] = df_clean['sypnopsis'].apply(lambda x:x.split())
df_clean['Rating'] = df_clean['Rating'].apply(lambda x:x.split())
df_clean['Type'] = df_clean['Type'].apply(lambda x:x.split())
df_clean['Studios'] = df_clean['Studios'].apply(lambda x:x.split())

In [33]:
df_clean['Genres'] = df_clean['Genres'].apply(lambda x: [i.replace(" ","") for i in x] )
df_clean['sypnopsis'] = df_clean['sypnopsis'].apply(lambda x: [i.replace(" ","") for i in x] )
df_clean['Rating'] = df_clean['Rating'].apply(lambda x: [i.replace(" ","") for i in x] )
df_clean['Type'] = df_clean['Type'].apply(lambda x: [i.replace(" ","") for i in x] )
df_clean['Studios'] = df_clean['Studios'].apply(lambda x: [i.replace(" ","") for i in x] )

In [34]:
df_clean

,MAL_ID,Name,Genres,sypnopsis,Type,Studios,Rating
0,1,Cowboy Bebop,"[Action, Adventure, Comedy, Drama, Sci-Fi, Space]","[In, the, year, 2071,, humanity, has, colonize...",[TV],[Sunrise],[17+]
1,5,Cowboy Bebop: Tengoku no Tobira,"[Action, Drama, Mystery, Sci-Fi, Space]","[other, day,, another, bounty—such, is, the, l...",[Movie],[Bones],[17+]
2,6,Trigun,"[Action, Sci-Fi, Adventure, Comedy, Drama, Sho...","[Vash, the, Stampede, is, the, man, with, a, $...",[TV],[Madhouse],[PG-13]
3,7,Witch Hunter Robin,"[Action, Mystery, Police, Supernatural, Drama,...","[ches, are, individuals, with, special, powers...",[TV],[Sunrise],[PG-13]
4,8,Bouken Ou Beet,"[Adventure, Fantasy, Shounen, Supernatural]","[It, is, the, dark, century, and, the, people,...",[TV],"[Toei, Animation]",[PG]
...,...,...,...,...,...,...,...
16211,48481,Daomu Biji Zhi Qinling Shen Shu,"[Adventure, Mystery, Supernatural]",[],[ONA],[],[]
16212,48483,Mieruko-chan,"[Comedy, Horror, Supernatural]","[ko, is, a, typical, high, school, student, wh...",[TV],[Passione],[]
16213,48488,Higurashi no Naku Koro ni Sotsu,"[Mystery, Dementia, Horror, Psychological, Sup...","[Sequel, to, Higurashi, no, Naku, Koro, ni, Go...",[TV],[],[17+]
16214,48491,Yama no Susume: Next Summit,"[Adventure, SliceofLife, Comedy]","[New, Yama, no, Susume, anime.]",[TV],[8bit],[PG-13]
16215,48492,Scarlet Nexus,"[Action, Fantasy]","[Solar, calendar, year, 2020:, grotesque, orga...",[TV],[Sunrise],[]

In [38]:
df = df_clean
df['tags'] = df['sypnopsis'] +df['Genres'] + df['Rating']+ df['Studios']+df['Type']

In [39]:
df =df[['MAL_ID', 'Name', 'tags']]

In [40]:
df

,MAL_ID,Name,tags
0,1,Cowboy Bebop,"[In, the, year, 2071,, humanity, has, colonize..."
1,5,Cowboy Bebop: Tengoku no Tobira,"[other, day,, another, bounty—such, is, the, l..."
2,6,Trigun,"[Vash, the, Stampede, is, the, man, with, a, $..."
3,7,Witch Hunter Robin,"[ches, are, individuals, with, special, powers..."
4,8,Bouken Ou Beet,"[It, is, the, dark, century, and, the, people,..."
...,...,...,...
16211,48481,Daomu Biji Zhi Qinling Shen Shu,"[Adventure, Mystery, Supernatural, ONA]"
16212,48483,Mieruko-chan,"[ko, is, a, typical, high, school, student, wh..."
16213,48488,Higurashi no Naku Koro ni Sotsu,"[Sequel, to, Higurashi, no, Naku, Koro, ni, Go..."
16214,48491,Yama no Susume: Next Summit,"[New, Yama, no, Susume, anime., Adventure, Sli..."
16215,48492,Scarlet Nexus,"[Solar, calendar, year, 2020:, grotesque, orga..."

In [41]:
df['tags'] = df['tags'].apply(lambda x: ' '.join(x) )
df['tags'] =df['tags'].apply(lambda x: x.lower())

In [42]:
df['tags'][0]

'in the year 2071, humanity has colonized several of the planets and moons of the solar system leaving the now uninhabitable surface of planet earth behind. the inter solar system police attempts to keep peace in the galaxy, aided in part by outlaw bounty hunters, referred to as "cowboys." the ragtag team aboard the spaceship bebop are two such individuals. mellow and carefree spike spiegel is balanced by his boisterous, pragmatic partner jet black as the pair makes a living chasing bounties and collecting rewards. thrown off course by the addition of new members that they meet in their travels—ein, a genetically engineered, highly intelligent welsh corgi; femme fatale faye valentine, an enigmatic trickster with memory loss; and the strange computer whiz kid edward wong—the crew embarks on thrilling adventures that unravel each member\'s dark and mysterious past little by little. well-balanced with high density action and light-hearted comedy, cowboy bebop is a space western classic and an homage to the smooth and improvised music it is named after. action adventure comedy drama sci-fi space 17+ sunrise tv'

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
cv = CountVectorizer(max_features =5000, stop_words ='english')

In [47]:
vector = cv.fit_transform(df['tags']).toarray()
vector.shape

(16195, 5000)

In [48]:
similarity = cosine_similarity(vector)
similarity

array([[1.        , 0.26605736, 0.13961986, ..., 0.06119901, 0.16760038,
        0.19038124],
       [0.26605736, 1.        , 0.14431272, ..., 0.06900656, 0.        ,
        0.08586776],
       [0.13961986, 0.14431272, 1.        , ..., 0.03168621, 0.17355253,
        0.03942849],
       ...,
       [0.06119901, 0.06900656, 0.03168621, ..., 1.        , 0.09128709,
        0.05184758],
       [0.16760038, 0.        , 0.17355253, ..., 0.09128709, 1.        ,
        0.11359237],
       [0.19038124, 0.08586776, 0.03942849, ..., 0.05184758, 0.11359237,
        1.        ]], shape=(16195, 16195))

In [53]:
df[df['Name']== 'Trigun'].index

Index([2], dtype='int64')

In [58]:
def recommend(anime):
    index = df[df['Name'] ==anime].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True, key = lambda x:x[1])
    for i in distances[1:6]:
        print(df.iloc[i[0]].Name)
        
recommend('Trigun')

No Guns Life 2nd Season
Duel Masters!
Inazma Delivery: Dougyousha Attack-hen
Konglong Baobei Zhi Longshen Yongshi
Trigun: Badlands Rumble

In [62]:
def recommend2(anime):
    index = df[df['Name'] ==anime].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True, key = lambda x:x[1])
    for i in distances[1:6]:
        print(df.iloc[i[0]].Name)
        print(df.iloc[i[0]].MAL_ID)
        
recommend2('Cowboy Bebop')

Top wo Nerae 3!
38273
Ginga Senpuu Braiger
4240
Seihou Tenshi Angel Links
1226
Konglong Baobei Zhi Longshen Yongshi
41416
Sputnik da One
41926

import pickle

In [60]:
import pickle

In [61]:
pickle.dump(df,open('anime_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))